[tool.poetry]
name = "paperboy"
version = "0.1.0"
description = ""
authors = ["alexbracken <ajbracken@bsu.edu>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
